#!/bin/bash
#
#--
# Copyright 2010 Red Hat, Inc.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#++
#

# Exit on errors.
set -e


#
# _main()
#
source $(cd -P -- "$(dirname -- "$0")/../hooks/" && pwd -P)/common.sh
params="<app-name> <app-guid> <connection-id>"
[ $# -ge 3 ]  ||  os_print_hook_usage "get document root" "$params"

# ./get_doc_root <app-name> <app-guid> <connection_id> => string 
#             (eg:file:///srv/webapps/132423423433423432/app)
conn_id=${3:-""}
os_log_debug "Get document root for '$conn_id'"

doc_root=${OPENSHIFT_APP_PROD_DIR:-"."}/$app_prod_subdir/
os_log_debug "Returning document root '$doc_root'"
echo "$doc_root"
exit 0

