#!/bin/bash
#
#--
# Copyright 2010 Red Hat, Inc.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#++
#

# Exit on errors.
set -e


#
# _main()
#
source $(cd -P -- "$(dirname -- "$0")/../hooks/" && pwd -P)/common.sh
params="<app-name> <app-guid> <connection-id>"
[ $# -ge 3 ]  ||  os_print_hook_usage "get php ini" "$params"

# ./get_php_ini <app-name> <app-guid> <connection_id> => string
# (eg:file:///srv/webapps/132423423433423432/app/vostok/setup/php-5/php.ini)
conn_id=${3:-""}

[ -n "$_DEBUG_HOOKS" ]  &&  os_log_debug "Get php ini for '$conn_id'"

comp_guid=${OPENSHIFT_COMPONENT_GUID:-""}
php_ini=${OPENSHIFT_APP_PROD_DIR:-"."}/$app_config_subdir/$comp_guid/php.ini

[ -n "$_DEBUG_HOOKS" ]  &&  os_log_debug "Returning php.ini '$php_ini'"
echo "$php_ini"
exit 0

