#!/bin/bash
#
#--
# Copyright 2010 Red Hat, Inc.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#++
#

# Exit on errors.
set -e


#
# Functions.
#
function init_substitution_map() {
   local server_name mapinfo
   [ -z "${os_vars_map[*]}" ]  &&  os_init_var_map

   vhost_name="${application_name}.${openshift_domain}"
   os_vars_map["$cartridge_name:VHOST_SERVER_NAME"]="$vhost_name"

   # The app-server still needs to substitute the app-server:BINDING variable.

   mapinfo="keys:[${!os_vars_map[@]}], values:[${os_vars_map[*]}]"
   os_log_debug "$FUNCNAME(): $mapinfo"
   return 0

}  #  End of function  init_substitution_map.


function copy_templates() {
   app_config_dir=${1:-"."}

   #  Ensure configuration exists for the component.
   if ! test -d "$app_config_dir/conf.d"; then
      mkdir -p "$app_config_dir/conf.d"
      local templates_dir
      templates_dir=$(cd -P "${hook_dir}/../templates" && pwd -P)
      for f in `(cd "$templates_dir"; find . -type f)`; do
         # Copy over the interpolated template to the app component space.
         os_copy_from_template "$templates_dir/$f" "$app_config_dir/$f"
      done
   fi

}  #  End of function  copy_templates.


#
# _main()
#
source $(cd -P -- "$(dirname -- "$0")" && pwd -P)/common.sh
[ $# -ge 1 ]  ||  os_print_hook_usage

init_substitution_map
copy_templates "${OPENSHIFT_HOOK_CONTEXT:-'.'}"


