#!/bin/bash
#
# Copyright © 2010 Red Hat, Inc. All rights reserved
#
# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.
#

# Exit on errors.
set -e

# Initialization.
cartridge_name="www-dynamic.apache2"
hook_name=$(basename "$0")
test $OPENSHIFT_TRACE_HOOKS && echo "!DEBUG! :$SHLVL: $hook_name $@"

source ./common.sh


#
# _main()
#
os_check_args "$@"  ||  print_usage "Start www-dynamic.apache2 Component"

app_guid=$1
component_guid=$2
declare -r platform_type=${_OPENSHIFT_PLATFORM_TYPE:-"/express"}

cfgdir="${_OPENSHIFT_APP_CONFIG_DIR:-"/tmp"}/$comp_guid"
cart_cfg_subdir="${cartridge_name}/conf"
cloc="${cfgdir}/${cart_cfg_subdir}"

#  First up need to ensure configuration exists for the component.
if ! test -f "${cloc}/httpd.conf"; then
   echo "Error: Missing configuration file - ${cloc}/httpd.conf" 2>
   exit 2
fi


#  Setup command line options.
httpd_opts="-C 'Include ${cfgdir}/${cartridge_name}/conf.d/*.conf'"

if [ "X$hook_name" = "Xstart" ]; then
   addrnport="$_OPENSHIFT_APP_BINDADDR:$_OPENSHIFT_APP_PORT"
   httpd_opts="${httpd_opts} -C 'Listen $addrnport'"
   httpd_opts="${httpd_opts} -C 'User  $_OPENSHIFT_APP_USER'"
   httpd_opts="${httpd_opts} -C 'Group $_OPENSHIFT_APP_GROUP'"
fi

/usr/sbin/httpd -f ${cfgdir}/httpd.conf ${httpd_opts} -k $hook_name

logger -p user.notice  "www-dynamic.apache2: $0 $@ + opts=${httpd_opts}"
