#!/bin/bash
#
#--
# Copyright 2010 Red Hat, Inc.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#++
#

# Exit on errors.
set -e


#
# _main()
#
source $(cd -P -- "$(dirname -- "$0")" && pwd -P)/common.sh
[ $# -ge 1 ]  ||  os_print_hook_usage

cfgfile="${OPENSHIFT_HOOK_CONTEXT:-'.'}/conf/httpd.conf"

#  Ensure configuration exists for the component.
if ! test -f "$cfgfile"; then
   die 2 "Missing configuration file - $cfgfile"
fi


#  Setup command line options.
user_name=`id -un`
group_name=`id -gn`

# If user is root, use the apache user/group.
[ "`id -u`" = "0" ]  &&  user_name="apache"  &&  group_name="apache"

rundir="${OPENSHIFT_APP_PROD_DIR:-"."}"
[ -d "$rundir/var/run" ]  ||  mkdir -p "$rundir/var/run"

cd "$rundir"
/usr/sbin/httpd -f $cfgfile -C "User $user_name" -C "Group $group_name"  \
                -k $hook_name
os_log_notice "$@ + opts=${httpd_opts}"
exit 0

