#!/bin/bash
#
#--
# Copyright 2010 Red Hat, Inc.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#++
#

# Exit on errors.
set -e


#
# Functions.
#
function init_substitution_map() {
   local cfg_dir mapinfo
   cfg_dir=${1:-'.'}
   [ -z "${!os_vars_map[@]}" ]  &&  os_init_var_map
   os_vars_map['php:CONFIGURATION_DIR']="$cfg_dir"
   os_vars_map['php:TEMPLATE_SESSION_SAVE_PATH']="$cfg_dir/sessions/"
   os_vars_map['php:TEMPLATE_UPLOAD_TMP_DIR']="$cfg_dir/tmp/"
   os_vars_map['php:www-dynamic:BIND_ADDRESS']=`os_get_userifaddr`

   for k in `env | egrep "^(php_www_dynamic)" | cut -f1 -d '='`; do
      os_vars_map["php:www-dynamic:${k:16}"]="${!k}"
   done

   mapinfo="keys:[${!os_vars_map[@]}], values:[${os_vars_map[*]}]"
   os_log_debug "$FUNCNAME(): $mapinfo"
   return 0

}  #  End of function  init_substitution_map.


function initialize_config_dir() {
   app_config_dir=${1:-"."}

   mkdir -p "${app_config_dir}/{etc,conf.d,sessions,tmp}"

   for d in docs ext php cache cfg data download temp tests www; do
      mkdir -p "${app_config_dir}/phplib/pear/$d"
   done

   ln -s /usr/lib64/httpd/modules "${app_config_dir}/modules"
   ln -s /etc/httpd/conf/magic    "${app_config_dir}/conf/magic"

}  #  End of function  initialize_config_dir.


function copy_php_scaffolding() {
   app_config_dir=${1:-"."}

   #  Ensure configuration exists for the component.
   if ! test -d "$app_config_dir/etc/conf"; then
      mkdir -p "$app_config_dir/etc/conf"

      local templates_dir
      templates_dir=$(cd -P "${hook_dir}/../templates" && pwd -P)
      for f in `(cd "$templates_dir"; find . -type f)`; do
         # Copy over the interpolated template to the app component space.
         os_copy_from_template "$templates_dir/$f" "$app_config_dir/$f"
      done
   fi

}  #  End of function  copy_php_scaffolding.


#
# _main()
#
source $(cd -P -- "$(dirname -- "$0")" && pwd -P)/common.sh
[ $# -ge 1 ]  ||  os_print_hook_usage

#  Source php's www-dynamic-server env.
source "$hook_dir/../templates/php-www-dynamic-server.env"

cfgdir=${OPENSHIFT_HOOK_CONTEXT:-"."}

#  Initialize config dir, substitution map, copy over scaffolding and init pear.
intialize_config_dir  "$cfgdir"
init_substitution_map "$cfgdir"
copy_php_scaffolding  "$cfgdir"
php_ensure_pear_env   "$cfgdir"

