#!/bin/bash
#
# Copyright © 2010 Red Hat, Inc. All rights reserved
#
# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.
#

# Exit on errors.
set -e


#
# _main()
#
source $(cd -P -- "$(dirname -- "$0")/../hooks/" && pwd -P)/common.sh
params="<app-name> <app-guid> <connection-id>"
[ $# -ge 3 ]  ||  os_print_hook_usage "get external uri" "$params"

# ./get_ext_uri <connection id>  => "http://ipaddr:8080"
conn_id=${3:-""}

[ -n "$_DEBUG_HOOKS" ]  &&  os_log_debug "Getting external uri for '$conn_id'"

comp_guid=${OPENSHIFT_COMPONENT_GUID:-""}
confd_dir=${OPENSHIFT_APP_PROD_DIR:-"."}/$app_config_subdir/$comp_guid/conf.d

listen_directive=$(grep -e "^\s*Listen" "$confd_dir/listen.conf")
protocol=$(echo "$listen_directive" | awk '{print $3}')
if [ -z "$protocol" ]; then
   [ -n "$_DEBUG_HOOKS" ]  &&  os_log_debug "Using default protocol - http"
   protocol=${protocol:-"http"}
fi

host_n_port=$(echo "$listen_directive" | awk '{print $2}')
[ -n "$_DEBUG_HOOKS" ]  &&  os_log_debug "host and port = $host_n_port"

[ -n "$_DEBUG_HOOKS" ]  &&  os_log_debug "Returning $protocol://$host_n_port/"
echo "$protocol://$host_n_port/"
exit 0

