#!/bin/bash
#
# Copyright © 2010 Red Hat, Inc. All rights reserved
#
# This copyrighted material is made available to anyone wishing to use, modify,
# copy, or redistribute it subject to the terms and conditions of the GNU
# General Public License v.2.  This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.  You should have
# received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
# incorporated in the source code or documentation are not subject to the GNU
# General Public License and may only be used or replicated with the express
# permission of Red Hat, Inc.
#

# Exit on errors.
set -e

#
# _initialize()
#
cartridge_name="www-dynamic"
script=$(basename "$0")
[ -n "$_TRACE_HOOKS" ] && set -x
[ -n "$_TRACE_HOOKS" ] && echo "!TRACE! :$SHLVL: $cartridge_name->$script $@"
parameter_info="<application-guid> <component-guid> <connection-id> <doc-root>"


#
# _main()
#
source ../hooks/common.sh
os_initialize_hook_env "${_OPENSHIFT_APP_CONFIG_DIR}"
[ $# -eq 4 ]  ||  die 1 "Usage: $cartridge_name->$script ${parameter_info}"

# ./set_doc_root <app_guid> <comp_guid> <connection id> <doc root>
# (eg:file:///srv/webapps/132423423433423432/app)

# Parameter values.
app_guid=$1
comp_guid=$2

cfgdir="${_OPENSHIFT_APP_CONFIG_DIR:-'.'}/$comp_guid"

#  Replace document root in any/all config files.
for d in conf conf.d; do
   for f in `ls "${cfgdir}/$cartridge_name/$d"`; do
      sed -i "s#\(\s*DocumentRoot[ \t]\)\(.*\)\$#\1 $3 #"   \
                "${cfgdir}/$cartridge_name/$d/$f"
   done
done

exit 0
