#!/bin/bash
#
#--
# Copyright 2010 Red Hat, Inc.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#++
#

# Exit on errors.
set -e


#
# _main()
#
source $(cd -P -- "$(dirname -- "$0")/../hooks/" && pwd -P)/common.sh
params="<app-name> <app-guid> <connection-id> <doc-root>"
[ $# -ge 4 ]  ||  os_print_hook_usage "set DocumentRoot" "$params"

# ./set_doc_root <app_name> <app_guid> <connection id> <doc root>
# (eg:file:///srv/webapps/132423423433423432/app)
conn_id=${3:-""}
docroot=${4:-""}
os_log_debug "Setting DocumentRoot to '$docroot' for '$conn_id'"

cfgdir=${OPENSHIFT_HOOK_CONTEXT:-"."}

#  Replace document root in any/all config files.
for f in `ls "$cfgdir/conf/"`; do
   cfile="$cfgdir/conf/$f"
   os_log_debug "Updating DocumentRoot in $cfile"
   sed -i "s#\(\s*DocumentRoot[ \t]\)\(.*\)\$#\1 $docroot #" "$cfile"
done

exit 0
